[package]
name = "obsidian"
version = "0.1.0"
authors = ["Gan Jun Kai <kuhn96@gmail.com>", "Wai Pai Lee <pailee.wai@gmail.com>"]
edition = "2018"
description = "A Rust framework"
repository = "https://github.com/jk-gan/obsidian"

license = "MIT"

[dependencies]
hyper = "0.12.15"
